name: LevelBorder
authors:
  - VenatusSaw
  - oskardotglobal
version: 1.2.0-SNAPSHOT
main: de.venatus247.levelborder.LevelBorder
softdepend:
  - VUtils

commands:
  levelborder:
    description: Setup the level border
